spring:
  kafka:
    ########### Kafka集群节点 ###########
    #bootstrap-servers: 192.168.10.100:9092,192.168.10.101:9092,192.168.10.102:9092
    bootstrap-servers: 10.0.0.9:9092
    # Kafka生产者
    producer:
      # 生产者发送失败后重发的次数
      retries: 0
      # Kafka key和value的序列化类
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        # 提交延时。0表示立即提交。
        linger.ms: 0
kafka-config:
  group:
    group1: group1
    group2: group2
    group3: group3
  topic:
    topic1: test_topic
    topic2: group_topic

